spring:
  application:
    name: tasks-service
  datasource:
    url: ${POSTGRESQL_URI}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI}/protocol/openid-connect/certs
server:
  port: ${PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}
